### ISSUE TITLE
[ONBOARDING]: Noa Tamir

### ISSUE THREAD

**Issue by trallard** [numfocus/DISC-committee#4]
# Onboarding checklist

## Access

- [x] GitHub
  - [x] Has been added to [DISC GitHub team](https://github.com/orgs/numfocus/teams/disc-steering-committee)
  - [x] Granted contributor rights to the  [DISC Repo](https://github.com/numfocus/DISC-committee)
- [x] Google
  - [x] DISC shared Google Drive
  - [x] DISC google group

- [x] Slack
  - [x] [NUMFOCUS Slack](numfocus.slack.com)
  - [x] disc-committee channel (private for the committee members only)

## Other actions

- [x] Have familiarised themselves with the WG charter
- [x] Have familiarised themselves with the meeting procedure

**Comment by arliss-NF** [comment]
NumFOCUS does not share with email addresses that don't have a gmail account linked so I am unable to add Noa to the shared drive.  I will continue to see if I can over-ride that restriction.

**Comment by noatamir** [comment]
👋 @arliss-NF I added my work email, which should resolve this issue for now

**Comment by arliss-NF** [comment]
@noatamir - the new email address worked.  You should be good to go.  Ping me if I've missed anything.

**Comment by trallard** [comment]
Closing as all has been marked as completed
