### ISSUE TITLE
[ONBOARDING]: Mark Mikofski

### ISSUE THREAD

**Issue by trallard** [numfocus/DISC-committee#6]
# Onboarding checklist

## Access

- [x] GitHub
  - [x] Has been added to [DISC GitHub team](https://github.com/orgs/numfocus/teams/disc-steering-committee)
  - [x] Granted contributor rights to the  [DISC Repo](https://github.com/numfocus/DISC-committee)
- [x] Google
  - [x] DISC shared Google Drive
  - [x] DISC google group

- [x] Slack
  - [x] [NUMFOCUS Slack](numfocus.slack.com)
  - [x] disc-committee channel (private for the committee members only)

## Other actions

- [x] Have familiarised themselves with the WG charter
- [ ] Have familiarised themselves with the meeting procedure

**Comment by mikofski** [comment]
- [x] read [wg charter](https://drive.google.com/drive/u/3/folders/0APPpeonS_fbQUk9PVA)
- [x] read [member responsibilities](https://github.com/numfocus/DISC-committee/blob/main/committee/members-responsibilities.md)
- [x] read [meeting process](https://github.com/numfocus/DISC-committee/blob/main/committee/meetings-process.md)
