### ISSUE TITLE
[MONTHLY]: June - steering committee meeting

### ISSUE THREAD

**Issue by trallard** [numfocus/DISC-committee#9]
## Before the meeting

- [x] Set agenda
- [x] Circulate agenda with all the committee members

## After the meeting

- [x] Review the meeting minutes
- [x] Create public minutes in the `./committee/public-meeting-minutes` folder
- [x] Open PR and Circulate with members for approval
- [x] Merge PR and publish to the <disc@numfocus.org> Google group

**Comment by trallard** [comment]
@mikofski - any updates on the minutes PR?

**Comment by mikofski** [comment]
@trallard I merged the June minutes PR but I don't think I can forward them to the disc@numfocus.org google group. Is this something you do or do I need to ask for access? thanks :)

**Comment by mikofski** [comment]
closed in #13
